[network]
name = "devnet"
node_rpc_address = "http://localhost:20443"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "fetch outside black test wash cover just actual execute nice door want airport betray quantum stamp fish act pen trust portion fatigue scissors vague"
balance = 1000000
# stx address: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
# btc address: mqVnk6NPRdhntvfm4hh9vvjiRkFDUuSYsH

[accounts.wallet_1]
mnemonic = "spoil sock coyote include verify comic relief quarter wide century always cable"
balance = 1000000
# stx address: ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5
# btc address: mr1iPkD9N3RJZZxXRk7xF9d36gffa6exNC

[accounts.wallet_2]
mnemonic = "arrange scale orient half ugly kid bike twin magnet joke hurt fiber"
balance = 1000000
# stx address: ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG
# btc address: muTnffLDR4u6PrP8jj1AjHKi2u9LR1YCMy

[accounts.wallet_3]
mnemonic = "glide mix tooth cool issue remember old visit parade broken stove virus"
balance = 1000000
# stx address: ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC
# btc address: mvZtbibDPXhZjMcpYkl2a8i2z5U2J1GRDM

[accounts.wallet_4]
mnemonic = "canvas dog science myself surface host process speed grit drive science curve"
balance = 1000000
# stx address: ST2NEB84ASENDXKYGJPQW86YXQCEFEX2ZQPG87ND
# btc address: mg1C76bNTutiCDV3t9nWhZs3Dc8LzFAXzE

[accounts.wallet_5]
mnemonic = "hurry aunt crane double pear baby force nerve segment wire cat lemon"
balance = 1000000
# stx address: ST2REHHS5J3CERCRBEPMGH7921Q6PYKAADT7JP2VB
# btc address: mweN5WVqadScHdA81aATSdcVr4B6dNokqx

[accounts.wallet_6]
mnemonic = "area desk dutch sign gold cricket dawn toward gigantic video weary raven"
balance = 1000000
# stx address: ST3AM1A56AK2C1XAFJ4115ZSV26EB49BVQ10MGCS0
# btc address: mzxXgV6e4BZSsz8zVHm3TmqbECt7pRhE6t

[accounts.wallet_7]
mnemonic = "prevent gallery kind limb income control noise together echo rival record wedding"
balance = 1000000
# stx address: ST3PF13W7Z0RRM42A8VZRVFQ75SV1K26RXEP8YGKJ
# btc address: n37mwmru2oaVosgfuvzBwgV2ysCQRrLko7

[accounts.wallet_8]
mnemonic = "vapor around more air around sound sight peanut other super tilt abandon"
balance = 1000000
# stx address: ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP
# btc address: n2v875jbJ4RjBnTjgbfikDfnwsDV5iUByw

[accounts.wallet_9]
mnemonic = "hold own kitten modify fire drink universe echo perfect vacant argue door"
balance = 1000000
# stx address: STNHKEPYEPJ8ET55ZZ0M5A34J0R3N5FM2CMMMAZ6
# btc address: mjSrB3wS4xab3kYqFktwBzfTdPg367ZJ2d
